#!/usr/bin/env python3
"""
Build submission_302.json: compliant robustness pass over submission_203.

This version does not chase locally uncovered continuation/else lines.  Instead
it reinforces target lines that are only covered once or twice locally and may
be the lines that disappear on the platform.
"""
import json
import re


BANNED = re.compile(
    r"\\!|\\i\b|base64|COPY\s+.*PROGRAM|COPY\s+.*\s+(FROM|TO)\s+'/"
    r"|LANGUAGE\s+'?c'?\b|LANGUAGE\s+internal|lo_(export|import)"
    r"|pg_read_file|pg_read_binary_file|\bgcc\b|pg_config|\.so\b"
    r"|pg_ls_dir|adminpack|\\gset|\\setenv|\\\s*echo"
    r"|\bDO\s*\$|\bLOOP\b|\bWHILE\b"
    r"|SET\s+ROLE|SET\s+SESSION\s+AUTHORIZATION",
    re.IGNORECASE | re.DOTALL,
)


ADDITIONS = {
    "127": [
        """
DROP TABLE IF EXISTS c127_rob_ref CASCADE;
DROP TABLE IF EXISTS c127_rob_parent CASCADE;
DROP TABLE IF EXISTS c127_rob_child CASCADE;
CREATE TABLE c127_rob_ref (id int PRIMARY KEY);
CREATE TABLE c127_rob_parent (
  id int NOT NULL,
  ref_id int NOT NULL REFERENCES c127_rob_ref(id)
) PARTITION BY LIST (id);
CREATE TABLE c127_rob_child (id int NOT NULL, ref_id int NOT NULL);
ALTER TABLE c127_rob_child
  ADD CONSTRAINT c127_rob_parent_ref_id_fkey CHECK (ref_id > 0);
INSERT INTO c127_rob_ref VALUES (1), (2), (3);
ALTER TABLE c127_rob_parent ATTACH PARTITION c127_rob_child FOR VALUES IN (1);
SELECT conname, contype
FROM pg_constraint
WHERE conrelid = 'c127_rob_child'::regclass
ORDER BY conname, contype;
DROP TABLE IF EXISTS c127_rob_parent CASCADE;
DROP TABLE IF EXISTS c127_rob_child CASCADE;
DROP TABLE IF EXISTS c127_rob_ref CASCADE;
""",
    ],
    "130": [
        """
SET client_min_messages = log;
SET debug_print_parse = on;
SET debug_pretty_print = off;
DROP TABLE IF EXISTS c130_rob CASCADE;
CREATE TABLE c130_rob (a int, b int, CONSTRAINT c130_rob_chk CHECK (a > 0));
ALTER TABLE c130_rob ADD CONSTRAINT c130_rob_notvalid CHECK (b > 0) NOT VALID;
ALTER TABLE c130_rob VALIDATE CONSTRAINT c130_rob_notvalid;
EXPLAIN (COSTS OFF) SELECT * FROM c130_rob WHERE a = 1;
RESET debug_print_parse;
RESET debug_pretty_print;
RESET client_min_messages;
DROP TABLE IF EXISTS c130_rob CASCADE;
""",
    ],
    "139": [
        """
DROP TABLE IF EXISTS c139_ident_rob CASCADE;
CREATE TABLE c139_ident_rob (id int GENERATED BY DEFAULT AS IDENTITY, v text);
INSERT INTO c139_ident_rob(v) VALUES ('a'), ('b');
ALTER TABLE c139_ident_rob ALTER COLUMN id TYPE bigint;
ALTER TABLE c139_ident_rob ALTER COLUMN id SET DATA TYPE numeric;
DROP TABLE IF EXISTS c139_ident_rob CASCADE;
""",
    ],
    "143": [
        """
DROP TABLE IF EXISTS c143_rob_parent CASCADE;
CREATE TABLE c143_rob_parent (id int, data text) PARTITION BY RANGE (id);
CREATE TABLE c143_rob_child1 PARTITION OF c143_rob_parent FOR VALUES FROM (1) TO (100);
CREATE TABLE c143_rob_child2 PARTITION OF c143_rob_parent FOR VALUES FROM (100) TO (200);
CREATE INDEX c143_rob_idx ON c143_rob_parent (id);
INSERT INTO c143_rob_parent SELECT i, 'v'||i FROM generate_series(1,150) i;
DROP INDEX c143_rob_idx;
DROP TABLE IF EXISTS c143_rob_parent CASCADE;
""",
    ],
    "146": [
        """
SET enable_hashjoin=off;
SET enable_nestloop=off;
SET enable_mergejoin=on;
SET enable_sort=off;
SET enable_seqscan=off;
DROP FUNCTION IF EXISTS c146rob_cmp(int,int) CASCADE;
CREATE FUNCTION c146rob_cmp(a int, b int) RETURNS int
LANGUAGE plpgsql IMMUTABLE AS $cmp$
BEGIN
  RETURN CASE WHEN a < b THEN -1 WHEN a > b THEN 1 ELSE 0 END;
END
$cmp$;
CREATE OPERATOR CLASS c146rob_oc FOR TYPE int4 USING btree AS
  OPERATOR 1 <, OPERATOR 2 <=, OPERATOR 3 =, OPERATOR 4 >=, OPERATOR 5 >,
  FUNCTION 1 c146rob_cmp(int,int);
DROP TABLE IF EXISTS c146rob_a CASCADE;
DROP TABLE IF EXISTS c146rob_b CASCADE;
CREATE TABLE c146rob_a(v int);
CREATE TABLE c146rob_b(v int);
INSERT INTO c146rob_a SELECT generate_series(1,150);
INSERT INTO c146rob_b SELECT generate_series(1,150);
CREATE INDEX c146rob_ai ON c146rob_a USING btree(v c146rob_oc);
CREATE INDEX c146rob_bi ON c146rob_b USING btree(v c146rob_oc);
ANALYZE c146rob_a;
ANALYZE c146rob_b;
CREATE OR REPLACE FUNCTION c146rob_cmp(a int, b int) RETURNS int
LANGUAGE plpgsql IMMUTABLE AS $cmp$
BEGIN
  RETURN CASE WHEN a < b THEN 1 WHEN a > b THEN -1 ELSE 0 END;
END
$cmp$;
SELECT count(*) FROM c146rob_a JOIN c146rob_b ON c146rob_a.v = c146rob_b.v;
DROP TABLE IF EXISTS c146rob_a CASCADE;
DROP TABLE IF EXISTS c146rob_b CASCADE;
DROP OPERATOR CLASS IF EXISTS c146rob_oc USING btree CASCADE;
DROP FUNCTION IF EXISTS c146rob_cmp(int,int) CASCADE;
RESET enable_hashjoin;
RESET enable_nestloop;
RESET enable_mergejoin;
RESET enable_sort;
RESET enable_seqscan;
""",
    ],
    "147": [
        """
DROP TABLE IF EXISTS c147_rob CASCADE;
CREATE TABLE c147_rob (id int NOT NULL, v text);
INSERT INTO c147_rob VALUES (1,'a'), (2,'b');
CREATE UNIQUE INDEX c147_rob_uidx ON c147_rob(id);
ALTER TABLE c147_rob ADD PRIMARY KEY USING INDEX c147_rob_uidx;
DROP TABLE IF EXISTS c147_rob CASCADE;
""",
    ],
}


def extract_blocks(text):
    return [b.strip() for b in re.findall(r"<sql>(.*?)</sql>", text, re.DOTALL | re.IGNORECASE)]


def wrap(blocks):
    parts = ["<test_cases>"]
    for i, block in enumerate(blocks, 1):
        parts += [
            f'  <test_case id="{i}">',
            f"    <description>cov_{i}</description>",
            "    <sql>",
            block.strip(),
            "    </sql>",
            "  </test_case>",
        ]
    parts.append("</test_cases>")
    return "\n".join(parts)


def main():
    submission = json.load(open("outputs/submission_203.json", encoding="utf-8"))
    appended = {}

    for item in submission:
        cid = str(item["id"])
        blocks = extract_blocks(item["generated_sql_tests"])
        if cid == "146":
            blocks = [
                block.replace(
                    "AS 91595 BEGIN RETURN CASE WHEN a > b THEN -1 WHEN a < b THEN 1 ELSE 0 END; END 91595",
                    "AS $cmp$ BEGIN RETURN CASE WHEN a > b THEN -1 WHEN a < b THEN 1 ELSE 0 END; END $cmp$",
                )
                for block in blocks
            ]
        seen = {b.strip() for b in blocks}
        for block in ADDITIONS.get(cid, []):
            clean = block.strip()
            if clean not in seen:
                blocks.append(clean)
                seen.add(clean)
                appended[cid] = appended.get(cid, 0) + 1
        item["generated_sql_tests"] = wrap(blocks)

    violations = []
    for item in submission:
        for idx, block in enumerate(extract_blocks(item["generated_sql_tests"]), 1):
            match = BANNED.search(block)
            if match:
                violations.append((item["id"], idx, match.group(0)))
    if violations:
        raise SystemExit(f"Banned constructs remain: {violations[:10]}")

    with open("outputs/submission_302.json", "w", encoding="utf-8") as f:
        json.dump(submission, f, ensure_ascii=False, indent=2)

    total_cases = sum(len(extract_blocks(item["generated_sql_tests"])) for item in submission)
    print("Wrote outputs/submission_302.json")
    print(f"Records: {len(submission)}")
    print(f"SQL cases: {total_cases}")
    print(f"Appended: {appended}")


if __name__ == "__main__":
    main()
